config/routes.rb
Rails.application.routes.draw do
  root "limes#index"
  resources :limes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lime.rb
class Lime < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/limes_controller.rb
class LimesController < ApplicationController
  before_action :set_lime, only: [:show, :edit, :update, :destroy]

  # GET /limes
  # GET /limes.json
  def index
    @limes = Lime.all
  end

  # GET /limes/1
  # GET /limes/1.json
  def show
  end

  # GET /limes/new
  def new
    @lime = Lime.new
  end

  # GET /limes/1/edit
  def edit
  end

  # POST /limes
  # POST /limes.json
  def create
    @lime = Lime.new(lime_params)

    respond_to do |format|
      if @lime.save
        format.html { redirect_to @lime, notice: 'Lime was successfully created.' }
        format.json { render :show, status: :created, location: @lime }
      else
        format.html { render :new }
        format.json { render json: @lime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /limes/1
  # PATCH/PUT /limes/1.json
  def update
    respond_to do |format|
      if @lime.update(lime_params)
        format.html { redirect_to @lime, notice: 'Lime was successfully updated.' }
        format.json { render :show, status: :ok, location: @lime }
      else
        format.html { render :edit }
        format.json { render json: @lime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /limes/1
  # DELETE /limes/1.json
  def destroy
    @lime.destroy
    respond_to do |format|
      format.html { redirect_to limes_url, notice: 'Lime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lime
      @lime = Lime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lime_params
      params.require(:lime).permit(:title, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/limes_helper.rb
module LimesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LIME</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/limes/_form.html.erb
<%= form_with(model: lime) do |form| %>
  <% if lime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lime.errors.count, "error") %> prohibited this lime from being saved:</h2>

      <ul>
        <% lime.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/limes/edit.html.erb
<h1>Editing Lime</h1>

<%= render 'form', lime: @lime %>

<%= link_to 'Show', @lime %> |
<%= link_to 'Back', limes_path %>

app/views/limes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Limes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @limes.each do |lime| %>
      <tr>
        <td><%= lime.title %></td>
        <td><%= lime.message %></td>
        <td><%= lime.name %><td>
        <td><%= link_to 'Show', lime %></td>
        <td><%= link_to 'Edit', edit_lime_path(lime) %></td>
        <td><%= link_to 'Destroy', lime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lime', new_lime_path %>

app/views/limes/new.html.erb
<h1>New Lime</h1>

<%= render 'form', lime: @lime %>

<%= link_to 'Back', limes_path %>

app/views/limes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lime.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @lime.message %>
</p>

<%= link_to 'Edit', edit_lime_path(@lime) %> |
<%= link_to 'Back', limes_path %>